apiVersion: apps/v1
kind: Deployment
metadata:
  name: silicon-dawn
  labels:
    app: silicon-dawn
spec:
  replicas: 1
  template:
    metadata:
      name: silicon-dawn
      labels:
        app: silicon-dawn
    spec:
      containers:
        - name: silicon-dawn
          image: skwrl/silicon-dawn:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3200
      restartPolicy: Always
  selector:
    matchLabels:
      app: silicon-dawn
---
apiVersion: v1
kind: Service
metadata:
  name: silicon-dawn
spec:
  selector:
    app: silicon-dawn
  ports:
    - port: 3200
      targetPort: 3200
      nodePort: 30032
      name: silicon-dawn-port
  type: NodePort
