---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: https://onlyhavecans.works/ops/ci-workflows/actions/go-lint@39b755b91f808b6b381d2d2d1c3baee2ecc3beb5 # v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: https://onlyhavecans.works/ops/ci-workflows/actions/go-test@39b755b91f808b6b381d2d2d1c3baee2ecc3beb5 # v1
        with:
          vendored: 'true'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: https://onlyhavecans.works/ops/ci-workflows/actions/go-build@39b755b91f808b6b381d2d2d1c3baee2ecc3beb5 # v1
        with:
          vendored: 'true'

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: goreleaser check
        uses: actions/goreleaser@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          distribution: goreleaser
          version: v2.13 # renovate datasource=github-releases depName=goreleaser/goreleaser
          args: check
