---
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47  # v9
        with:
          version: v2.4

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
