---
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9
        with:
          version: v2.4

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6
        with:
          go-version: stable

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
