---
name: docker-deploy

on:
  push:
    branches:
      - main

env:
  CACHE_KEY: 2024-03-06

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8  # v6
        id: cache
        with:
          path: ./data
          key: cards-${{ env.CACHE_KEY }}
          restore-keys: |
            cards-

      - name: Download cards
        if: steps.cache.outputs.cache-hit == false
        run: |
          curl -OL "http://egypt.urnash.com/media/blogs.dir/1/files/2018/01/The-Tarot-of-the-Silicon-Dawn.zip"
          mkdir -p ./data
          unzip -oj The-Tarot-of-the-Silicon-Dawn.zip -x "__MACOSX/*" "*/sand-home*" -d ./data

      - name: Set up Docker Buildx
        uses: actions/setup-buildx@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
        with:
          driver-opts: |
            network=host

      - name: Login to Docker Hub
        uses: actions/login-docker@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: actions/build-push-docker@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          push: true
          tags: skwrl/silicon-dawn:latest
