---
name: docker-deploy

on:
  push:
    branches:
      - main

env:
  CACHE_KEY: cards-2024-03-06

jobs:
  cache-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install just
        run: |
          sudo apt-get update
          sudo apt install just -y

      - name: Cache cards
        id: cache-cards
        uses: actions/cache@v4
        with:
          path: data
          key: ${{ env.CACHE_KEY }}

      - name: Download cards
        if: steps.cache-cards.outputs.cache-hit == false
        run: |
          just ensure-cards

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: data
          key: ${{ env.CACHE_KEY }}

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: https://github.com/docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: skwrl/silicon-dawn:latest
