---
name: docker-deploy

on:
  push:
    branches:
      - 'main'

env:
  CACHE_KEY: 2023-08-23

jobs:
  cache-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache cards
        id: cache-cards
        uses: actions/cache@v3
        with:
          path: data
          key: ${{ env.CACHE_KEY }}

      - name: Download cards
        if: steps.cache-cards.outputs.cache-hit == false
        run: >
          make data

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: data
          key: ${{ env.CACHE_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skwrl/silicon-dawn:latest
